#!/bin/bash
make clean
make

# with strassen algorithm
for DIM in {10..500..10}
do
    rel/foo $DIM 0
done
# without strassen algorithm
for DIM in {10..500..10}
do
    rel/foo $DIM 1
done

# check correctness
for DIM in {10..500..10}
do
    rel/foo $DIM 2
done

# using different breaks with strassen algorithm
let "BREAKS=1"
for i in {1..8}
do
    let "BREAKS = BREAKS * 2"
#    echo $BREAKS
    rel/foo 500 0 $BREAKS
done
